/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "#e4eaf3",
        surface: "#eef3f9",
        "surface-raised": "#f5f8fc",
        "surface-muted": "#dce4ef",
        "surface-container": "#f0f4fa",
        "surface-container-low": "#e8eef6",
        "surface-container-high": "#fafcfe",
        "surface-container-lowest": "#dde5f0",
        "on-surface": "#1e293b",
        "on-surface-variant": "#64748b",
        "on-background": "#334155",
        outline: "#c5d0e0",
        "outline-variant": "#d8e2ee",
        primary: "#5b5ef7",
        "primary-container": "#7c7ffa",
        "primary-fixed-dim": "#4f46e5",
        "on-primary": "#ffffff",
        secondary: "#0891b2",
        "secondary-container": "#22d3ee",
        "on-secondary": "#ffffff",
        tertiary: "#6366f1",
        "on-tertiary": "#ffffff",
        error: "#dc2626",
        "error-container": "#fef2f2",
        "on-error": "#ffffff",
        accent: "#0ea5e9",
        tech: {
          grid: "#cbd5e1",
          glow: "#818cf8",
          cyan: "#06b6d4",
        },
      },
      borderRadius: {
        DEFAULT: "1rem",
        lg: "1.25rem",
        xl: "1.5rem",
        "2xl": "1.75rem",
        full: "9999px",
      },
      spacing: {
        gutter: "24px",
        unit: "4px",
        "margin-mobile": "16px",
        "container-max-width": "1440px",
        "margin-desktop": "40px",
      },
      fontFamily: {
        "headline-lg": ["Geist", "Inter", "sans-serif"],
        "body-lg": ["Geist", "Inter", "sans-serif"],
        "display-lg": ["Geist", "Inter", "sans-serif"],
        "headline-lg-mobile": ["Geist", "Inter", "sans-serif"],
        "label-sm": ["JetBrains Mono", "monospace"],
        "body-md": ["Geist", "Inter", "sans-serif"],
        "headline-md": ["Geist", "Inter", "sans-serif"],
        "label-md": ["JetBrains Mono", "monospace"],
        sans: ["Geist", "Inter", "sans-serif"],
      },
      fontSize: {
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.04em", fontWeight: "700" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "500" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.05em", fontWeight: "500" }],
      },
      backgroundImage: {
        "tech-grid": `linear-gradient(rgba(99, 102, 241, 0.04) 1px, transparent 1px),
          linear-gradient(90deg, rgba(99, 102, 241, 0.04) 1px, transparent 1px)`,
        "tech-gradient": "linear-gradient(135deg, #eef3f9 0%, #e4eaf3 50%, #dce8f4 100%)",
      },
      backgroundSize: {
        grid: "24px 24px",
      },
      animation: {
        "slide-in": "slideIn 0.3s ease-out",
        "fade-in": "fadeIn 0.4s ease-out",
        "scale-in": "scaleIn 0.2s ease-out",
        "pulse-slow": "pulse 3s ease-in-out infinite",
        shimmer: "shimmer 1.5s infinite",
        float: "float 3s ease-in-out infinite",
        "gradient-move": "gradientMove 5s ease infinite",
      },
      keyframes: {
        slideIn: {
          "0%": { transform: "translateX(-10px)", opacity: "0" },
          "100%": { transform: "translateX(0)", opacity: "1" },
        },
        fadeIn: {
          "0%": { opacity: "0", transform: "translateY(8px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        scaleIn: {
          "0%": { transform: "scale(0.95)", opacity: "0" },
          "100%": { transform: "scale(1)", opacity: "1" },
        },
        shimmer: {
          "0%": { backgroundPosition: "-200px 0" },
          "100%": { backgroundPosition: "calc(200px + 100%) 0" },
        },
        float: {
          "0%, 100%": { transform: "translateY(0)" },
          "50%": { transform: "translateY(-6px)" },
        },
        gradientMove: {
          "0%": { backgroundPosition: "0% 50%" },
          "50%": { backgroundPosition: "100% 50%" },
          "100%": { backgroundPosition: "0% 50%" },
        },
      },
      boxShadow: {
        neo: "8px 8px 20px #c5d0de, -6px -6px 18px #ffffff",
        "neo-sm": "4px 4px 14px #c5d0de, -3px -3px 12px #ffffff",
        "neo-lg": "12px 12px 28px #b8c5d8, -8px -8px 24px #ffffff",
        "neo-inset": "inset 4px 4px 12px #c5d0de, inset -3px -3px 10px #ffffff",
        "neo-pressed": "inset 5px 5px 14px #b8c5d6, inset -4px -4px 12px #fafcff",
        card: "8px 8px 20px #c5d0de, -5px -5px 16px #ffffff",
        "card-hover": "10px 12px 28px #b8c5d8, -6px -6px 20px #ffffff, 0 0 0 1px rgba(99, 102, 241, 0.08)",
        glow: "0 0 24px rgba(99, 102, 241, 0.2)",
        "glow-cyan": "0 0 20px rgba(8, 145, 178, 0.25)",
        "glow-amber": "0 0 16px rgba(245, 158, 11, 0.2)",
      },
    },
  },
  plugins: [],
};
