/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "#faf8f6",
        surface: "#ffffff",
        "surface-raised": "#fffbf7",
        "surface-muted": "#f5ebe3",
        "surface-container": "#ffffff",
        "surface-container-low": "#fff7ed",
        "surface-container-high": "#ffffff",
        "surface-container-lowest": "#ffedd5",
        "on-surface": "#1e293b",
        "on-surface-variant": "#64748b",
        "on-background": "#334155",
        outline: "#eadfce",
        "outline-variant": "#fde8d4",
        primary: "#f97316",
        "primary-container": "#fb923c",
        "primary-fixed-dim": "#ea580c",
        "on-primary": "#ffffff",
        secondary: "#f59e0b",
        "secondary-container": "#fbbf24",
        "on-secondary": "#ffffff",
        tertiary: "#c2410c",
        "on-tertiary": "#ffffff",
        error: "#dc2626",
        "error-container": "#fef2f2",
        "on-error": "#ffffff",
        accent: "#fdba74",
        tech: {
          grid: "#fde8d4",
          glow: "#fb923c",
          cyan: "#fbbf24",
        },
      },
      borderRadius: {
        DEFAULT: "1rem",
        lg: "1.25rem",
        xl: "1.5rem",
        "2xl": "1.75rem",
        full: "9999px",
      },
      spacing: {
        gutter: "24px",
        unit: "4px",
        "margin-mobile": "16px",
        "container-max-width": "1440px",
        "margin-desktop": "40px",
      },
      fontFamily: {
        "headline-lg": ["Geist", "Inter", "sans-serif"],
        "body-lg": ["Geist", "Inter", "sans-serif"],
        "display-lg": ["Geist", "Inter", "sans-serif"],
        "headline-lg-mobile": ["Geist", "Inter", "sans-serif"],
        "label-sm": ["JetBrains Mono", "monospace"],
        "body-md": ["Geist", "Inter", "sans-serif"],
        "headline-md": ["Geist", "Inter", "sans-serif"],
        "label-md": ["JetBrains Mono", "monospace"],
        sans: ["Geist", "Inter", "sans-serif"],
      },
      fontSize: {
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.04em", fontWeight: "700" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "500" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.05em", fontWeight: "500" }],
      },
      backgroundImage: {
        "tech-grid": `linear-gradient(rgba(249, 115, 22, 0.05) 1px, transparent 1px),
          linear-gradient(90deg, rgba(249, 115, 22, 0.05) 1px, transparent 1px)`,
        "tech-gradient": "linear-gradient(135deg, #ffffff 0%, #fff7ed 50%, #ffedd5 100%)",
        "brand-gradient": "linear-gradient(135deg, #fb923c 0%, #f97316 50%, #ea580c 100%)",
      },
      backgroundSize: {
        grid: "24px 24px",
      },
      animation: {
        "slide-in": "slideIn 0.3s ease-out",
        "fade-in": "fadeIn 0.4s ease-out",
        "scale-in": "scaleIn 0.2s ease-out",
        "pulse-slow": "pulse 3s ease-in-out infinite",
        shimmer: "shimmer 1.5s infinite",
        float: "float 3s ease-in-out infinite",
        "gradient-move": "gradientMove 5s ease infinite",
      },
      keyframes: {
        slideIn: {
          "0%": { transform: "translateX(-10px)", opacity: "0" },
          "100%": { transform: "translateX(0)", opacity: "1" },
        },
        fadeIn: {
          "0%": { opacity: "0", transform: "translateY(8px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        scaleIn: {
          "0%": { transform: "scale(0.95)", opacity: "0" },
          "100%": { transform: "scale(1)", opacity: "1" },
        },
        shimmer: {
          "0%": { backgroundPosition: "-200px 0" },
          "100%": { backgroundPosition: "calc(200px + 100%) 0" },
        },
        float: {
          "0%, 100%": { transform: "translateY(0)" },
          "50%": { transform: "translateY(-6px)" },
        },
        gradientMove: {
          "0%": { backgroundPosition: "0% 50%" },
          "50%": { backgroundPosition: "100% 50%" },
          "100%": { backgroundPosition: "0% 50%" },
        },
      },
      boxShadow: {
        neo: "8px 8px 20px #eadfce, -6px -6px 18px #ffffff",
        "neo-sm": "4px 4px 14px #eadfce, -3px -3px 12px #ffffff",
        "neo-lg": "12px 12px 28px #e5d4c4, -8px -8px 24px #ffffff",
        "neo-inset": "inset 4px 4px 12px #eadfce, inset -3px -3px 10px #ffffff",
        "neo-pressed": "inset 5px 5px 14px #e5d4c4, inset -4px -4px 12px #fffbf7",
        card: "8px 8px 20px #eadfce, -5px -5px 16px #ffffff",
        "card-hover": "10px 12px 28px #e5d4c4, -6px -6px 20px #ffffff, 0 0 0 1px rgba(249, 115, 22, 0.1)",
        glow: "0 0 24px rgba(249, 115, 22, 0.25)",
        "glow-cyan": "0 0 20px rgba(251, 191, 36, 0.3)",
        "glow-amber": "0 0 16px rgba(245, 158, 11, 0.25)",
      },
    },
  },
  plugins: [],
};
